#!/bin/bash
. /opt/local/perlbrew/etc/bashrc
eval $( perl -Mlocal::lib )

export MOJO_HOME=$(pwd)
export BEAM_PATH=$HOME/etc/container
export BEAM_MINION=sqlite:////home/cpantesters/var/db/minion.sqlite

exec beam minion worker report
